export const Users = [
  {
    id: 1,
    profilePicture: '/assets/person/1.jpeg',
    username: 'Shri Om Trivedi',
    bio: 'Upcoming Enterpreneur',
  },
  {
    id: 2,
    profilePicture: '/assets/person/2.jpeg',
    username: 'Vinsmoke Sanji',
    bio: 'I like cooking',
  },
  {
    id: 3,
    profilePicture: '/assets/person/3.jpeg',
    username: 'Tripti Patil',
    bio: 'I like to travel',
  },
  {
    id: 4,
    profilePicture: '/assets/person/4.jpeg',
    username: 'Dora Hawks',
    bio: 'The map says whattt!!!?',
  },
  {
    id: 5,
    profilePicture: '/assets/person/5.jpeg',
    username: 'Riri Williams',
    bio: 'I like to play football',
  },
  {
    id: 6,
    profilePicture: '/assets/person/6.jpeg',
    username: 'Shirley Beauchamp',
    bio: 'You know what I like?',
  },
  // {
  //   id: 7,
  //   profilePicture: '/assets/person/7.jpeg',
  //   username: 'Michael Caine',
  // },
  // {
  //   id: 8,
  //   profilePicture: '/assets/person/8.jpeg',
  //   username: 'Kristen Thomas',
  // },
  // {
  //   id: 9,
  //   profilePicture: '/assets/person/9.jpeg',
  //   username: 'Gary Duty',
  // },
  // {
  //   id: 10,
  //   profilePicture: '/assets/person/10.jpeg',
  //   username: 'Kamado Tanjirou',
  // },
];

export const Posts = [
  {
    id: 1,
    desc: 'Love For All, Hatred For None.',
    photo: '/assets/post/1.jpeg',
    date: '5 mins ago',
    userId: 1,
    like: 0,
    comment: 9,
  },
  {
    id: 2,
    photo: '/assets/post/2.jpeg',
    date: '15 mins ago',
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: 'Every moment is a fresh beginning.',
    photo: '/assets/post/3.jpeg',
    date: '1 hour ago',
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: '/assets/post/4.jpeg',
    date: '4 hours ago',
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: '/assets/post/5.jpeg',
    date: '5 hours ago',
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: '/assets/post/6.jpeg',
    date: '1 day ago',
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: 'Never regret anything that made you smile.',
    photo: '/assets/post/7.jpeg',
    date: '2 days ago',
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: '/assets/post/8.jpeg',
    date: '3 days ago',
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: 'Change the world by being yourself.',
    date: '5 days ago',
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: '/assets/post/10.jpeg',
    date: '1 week ago',
    userId: 10,
    like: 104,
    comment: 12,
  },
];

export const trendingNews = [
  {
    id: 1,
    content: "The new iPhone X is out and it's not bad at all",
    user: 'John Jacobs',
    date: '2d',
    views: 30,
  },
  {
    id: 2,
    content: 'Pizza is the best food ever',
    user: 'Kimi Raikkonen',
    date: '3d',
    views: 20,
  },
  {
    id: 3,
    content: 'kanye west is the best rapper ever',
    user: 'wiz khalifa',
    date: '4d',
    views: 10,
  },
  {
    id: 4,
    content: 'David beckham is the best footballer',
    user: 'Hulk Hogan',
    date: '5d',
    views: 40,
  },
  {
    id: 5,
    content: 'How I met your mother is the best show ever',
    user: 'Ted Mosby',
    date: '6d',
    views: 50,
  },
  {
    id: 6,
    content: 'Cody Rhodes is the best wrestler ever',
    user: 'Lebron James',
    date: '7d',
    views: 60,
  },
];

export const jobs = [
  {
    id: 1,
    title: 'Software Engineer',
    company: 'Google',
    location: 'Mountain View, CA',
    date: '2 weeks ago',
  },
  {
    id: 2,
    title: 'Senior Software Engineer',
    company: 'Facebook',
    location: 'Menlo Park, CA',
    date: '2 weeks ago',
  },
  {
    id: 3,
    title: 'Devops Engineer',
    company: 'Apple',
    location: 'Cupertino, CA',
    date: '4 months ago',
  },
  {
    id: 4,
    title: 'Cloud Engineer',
    company: 'Amazon',
    location: 'Seattle, WA',
    date: '3 days ago',
  },
  {
    id: 5,
    title: 'Testing Engineer',
    company: 'Microsoft',
    location: 'Bangalore, KA',
    date: '2 days ago',
  },
  {
    id: 6,
    title: 'UI Engineer',
    company: 'Cred',
    location: 'Bangalore, KA',
    date: '7 days ago',
  },
];
