import React from "react";
import "./rightbar.css";

const rightbar = () => {
  return (
    <div className="rightbar">
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
      <h1>bye</h1>
    </div>
  );
};

export default rightbar;
